### ISSUE TITLE
Limite do tamanho de numero de fax. R10

### ISSUE THREAD

**Issue by gustavoamorimqueiroz** [samuelroliveira/SINTEGRABr#3]
Quando insiro um telefone (campo fax no registro 10) com tamanho maior do que 10 posições, por exemplo 12 posições, então é gerado no arquivo do sintegra as 12 posições enquanto deveria ser refatorado para o tamanho 10.

**Comment by samuelroliveira** [comment]
Fala @gustavoamorimqueiroz, tudo na paz?

Fiz a correção no commit https://github.com/samuelroliveira/SINTEGRABr/commit/83f77a0304a4a9323fb6d48082d2975571ea861c.

Abs.

**Comment by gustavoamorimqueiroz** [comment]
Olá. Tudo na paz!!!
Muito obrigado.
Abs.
