### ISSUE TITLE
Casas decimais em valor de venda bruta R60M

### ISSUE THREAD

**Issue by gustavoamorimqueiroz** [samuelroliveira/SINTEGRABr#4]
Olá,
A quantidade de casas decimais em valor de venda bruta R60M deve ser 2, porém está 0. Linha 76 Registro60M.
No manual não fala a quantidade porém é um numérico e dá erro se não colocar, portanto é bem provável que seja com 2 casas decimais mesmo. Testei com 2 casas e deu certo aqui! 

Desde já obrigado.

**Comment by samuelroliveira** [comment]
@gustavoamorimqueiroz fiz essa correção do 60M no commit https://github.com/samuelroliveira/SINTEGRABr/commit/29f46f1b0e6de864e9214d1f5e060db7f93a65d5.
Lembrei que você havia comentado que o registro 75 não estava limitando ao tamanho do campo, aproveitei e fiz a correção também.
