### ISSUE TITLE
campo Situação 	  Situação da Nota Fiscal 	  1 	  126 	  126 	  X

### ISSUE THREAD

**Issue by robertorp** [samuelroliveira/SINTEGRABr#7]
![image](https://user-images.githubusercontent.com/10251705/45366495-5b48b600-b5b5-11e8-871b-bf1cfced8382.png)

Quais os valores validos para esse campo?
em um exemplo de sintegra tem o valor "N" e valor "4"

blz mas onde encontro todos os campos válidos para isso?

Registro 50

**Comment by samuelrochaoliveira** [comment]
Fala @robertorp, tudo na paz?

Os valores válidos são:
![image](https://user-images.githubusercontent.com/15462690/45368430-f479cb80-b5b9-11e8-93be-bf1943fd5c86.png)

Encontrados no [Manual do Convênio 57/95](https://www.confaz.fazenda.gov.br/legislacao/convenios/1995/CV057_95_manualOrien2) (Que instituiu o SINTEGRA), no site do CONFAZ (Conselho e Política Fazendária).

Aqui o link do [Convênio 57/95](https://www.confaz.fazenda.gov.br/legislacao/convenios/1995/CV057_95).

PS: Ao abrir o link pesquise por "11 - REGISTRO TIPO 50" e logo você encontrará a seção do Registro Tipo 50.

Abraços.
